services:
  video_feed_crawler:
    container_name: video_feed_crawler
    build:
      context: .
      dockerfile: dockerfile
      tags:
        - "localhost:5000/video_feed_crawler:1.0"

    image: "localhost:5000/video_feed_crawler:1.0"

    command: uv run main.py