services:
  video_feed_crawler:
    container_name: video_feed_crawler
    build:
      context: .
      dockerfile: dockerfile
      tags:
        - "ghcr.io/huzaifairfan/video_feed_crawler:0.1"
        
    image: "ghcr.io/huzaifairfan/video_feed_crawler:0.1"
    restart: unless-stopped

    environment:
      - UV_LINK_MODE=copy
      - SELENIUM_URL=http://selenium_chrome:4444/wd/hub
      - MONGODB_URI=mongodb://mongodb:27017/
      - DATABASE=video_feed_crawler
      - CELERY_BROKER_URL=redis://redis:6379/0
      
      
    command: >
      sh -c "celery -A celery_app beat --loglevel=info & 
             celery -A celery_app worker --loglevel=info"

    networks:
      - video_feed_crawler
    depends_on:
      selenium_chrome:
        condition: service_healthy
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy

    healthcheck:
      test: ["CMD", "celery", "-A", "celery_app", "inspect", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
      

  mongodb:
    container_name: mongodb
    image: mongo:8-noble
    restart: unless-stopped
    
    ports:
      - '27017:27017'
    volumes:
      - mongodb:/data/db
    networks:
      - video_feed_crawler
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  selenium_chrome:
    container_name: selenium_chrome
    image: selenium/standalone-chrome:130.0-chromedriver-130.0-20250414
    restart: unless-stopped

    ports:
      - "4444:4444"
      - "7900:7900"
    networks:
      - video_feed_crawler
    shm_size: "2g"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4444/wd/hub/status"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  redis:
    container_name: redis
    image: redis:7.4-alpine
    restart: unless-stopped
    command: redis-server 

    ports:
      - '6379:6379'
    volumes: 
      - redis:/data
    networks:
      - video_feed_crawler

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s


volumes:
  redis:
    driver: local
  mongodb:
    driver: local

networks:
  video_feed_crawler:
    driver: bridge
