ARG UV_VERSION=0.6.16
ARG DISTRO_VERSION=noble


FROM ghcr.io/astral-sh/uv:$UV_VERSION AS uv


FROM mcr.microsoft.com/devcontainers/base:$DISTRO_VERSION
LABEL maintainer="HuzaifaIrfan <contact@huzaifairfan.com>"


# # hadolint ignore=DL3008
# RUN apt-get update \
#     && apt-get install -y \
#     # For OpenCV PYQT5 etc...
#     python3-opencv python3-pyqt5\
#     # To remove the image size, it is recommended refresh the package cache as follows
#     && apt-get clean \
#     && rm -rf /var/lib/apt/lists/*

# --chown=vscode:
COPY --from=uv /uv /uvx /bin/

RUN mkdir -p /home/vscode/.cache/uv && \
    chown -R vscode:vscode /home/vscode/.cache