services:
  video_feed_crawler-dev:
    container_name: video_feed_crawler-dev
    build:
      context: .
      dockerfile: dockerfile
      tags:
        - "localhost:5000/video_feed_crawler-dev:1.0"

    environment:
      - UV_LINK_MODE=copy
      - SELENIUM_URL=http://selenium_chrome:4444/wd/hub
      - MONGODB_URI=mongodb://mongodb:27017/
      - DATABASE=video_feed_crawler
      
    extra_hosts:
      - "host.docker.internal:host-gateway"

    volumes:
      - uv-vscode-cache:/home/vscode/.cache/uv
      
    command: /bin/sh -c "while sleep 1000; do :; done"

    depends_on:
      - selenium_chrome
      - mongodb

  selenium_chrome:
    image: selenium/standalone-chrome:130.0-chromedriver-130.0-20250414
    ports:
      - "4444:4444"
      - "7900:7900"
    shm_size: "2g"

  mongodb:
    container_name: mongodb
    image: mongo:8-noble
    ports:
      - '27017:27017'
    volumes:
      - mongodb:/data/db
    restart: unless-stopped 


volumes:
  mongodb:
    driver: local
  uv-vscode-cache:
    driver: local