name: Continuous Delivery Workflow

on:
  push:
    branches:
      - prod  # You can change this to the branch you want to target

jobs:
  build-test-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry (ghcr.io)
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker images using Docker Compose
      run: |
        docker compose build

    - name: Run tests with Docker Compose
      run: |
        docker compose up --no-start
        docker compose run --rm video_feed_crawler uv run pytest
        docker compose down

    - name: Push images with Docker Compose
      run: |
        docker compose push